# Generated by Django 5.1.1 on 2024-10-28 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_review_sentiment_alter_review_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='gif_url',
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app.product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='sentiment',
            field=models.CharField(choices=[('Good', 'Good'), ('Neutral', 'Neutral'), ('Weak', 'Weak')], max_length=10),
        ),
    ]
