# Generated by Django 5.1.1 on 2024-10-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_productimage_gif_url_alter_review_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='sentiment',
            field=models.CharField(blank=True, choices=[('Good', 'Good'), ('Neutral', 'Neutral'), ('Weak', 'Weak')], max_length=10),
        ),
    ]
