# Generated by Django 5.1.1 on 2024-10-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_review_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, 'Bad'), (2, 'Weak'), (3, 'Neutral'), (4, 'Good'), (5, 'Excellent')]),
        ),
    ]
