# Generated by Django 5.1.1 on 2024-10-28 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_orderplaced_qr_code_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='qr_code',
        ),
    ]
