# Generated by Django 5.1.1 on 2024-10-29 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
