# Generated by Django 5.1.1 on 2024-10-29 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_orderplaced_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='qr_code',
        ),
    ]
